force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Represents an event meetup, which users can register for.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>A generated code that can be used to find this meetup on the registration page.</description>
    <externalId>true</externalId>
    <inlineHelpText>A generated code that can be used to find this meetup on the registration page.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The max number of registrations allowed for this Meetup.</description>
    <inlineHelpText>The max number of registrations allowed for this Meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Meetup.</description>
    <inlineHelpText>The status of the Meetup.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Represents an individual registration for a related meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup that this registration relates to.</description>
    <inlineHelpText>The meetup that this registration relates to.</inlineHelpText>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupService.cls
/* 
* @description Handles operations related to Meetups.
*/
public with sharing class MeetupService {
    
    /* 
	* @description Returns a meetup that can be registered for (it exists, is open, and has capacity).
    * @param registrationCode The unique registration code of the meetup to evaluate.
    * @return Meetup__c the meetup if it's registerable, otherwise null.
    */
    @AuraEnabled(cacheable=true)
    public static Meetup__c getRegisterableMeetup(String registrationCode) {
        List<Meetup__c> openMeetups = [
            SELECT Id, Name, RegistrationLimit__c,
                (SELECT Id FROM MeetupRegistrations__r)
            FROM Meetup__c
            WHERE RegistrationCode__c = :registrationCode
            AND Status__c = 'Open'
            LIMIT 1
        ];

        if (openMeetups.isEmpty()) {
            return null;
        }

        Meetup__c openMeetup = openMeetups[0];
        if (openMeetup.RegistrationLimit__c <= openMeetup.MeetupRegistrations__r.size()) {
            return null;
        }

        // Limit data returned to client.
        return new Meetup__c(Id = openMeetup.Id, Name = openMeetup.Name);
    }
}