force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Represents an event meetup, which users can register for.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The max number of registrations allowed for this Meetup.</description>
    <inlineHelpText>The max number of registrations allowed for this Meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Meetup.</description>
    <inlineHelpText>The status of the Meetup.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Represents an individual registration for a related meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The registrant&apos;s email address.</description>
    <inlineHelpText>The registrant&apos;s email address.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>The first name of the registrant.</description>
    <inlineHelpText>The first name of the registrant.</inlineHelpText>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>The last name of the registrant.</description>
    <inlineHelpText>The last name of the registrant.</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup that this registration relates to.</description>
    <inlineHelpText>The meetup that this registration relates to.</inlineHelpText>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationServiceTest.cls
@isTest
private with sharing class MeetupRegistrationServiceTest {
    
    @isTest
    private static void isEmailRegistered_existingRegistration_expectTrue(){
        Meetup__c testMeetup = new Meetup__c(
            Name = 'Unit Test Meetup',
            Status__c = 'Open',
            RegistrationLimit__c = 1
        );

        insert testMeetup;

        MeetupRegistration__c testMeetupRegistration = new MeetupRegistration__c(
            Meetup__c = testMeetup.Id,
            FirstName__c = 'First',
            LastName__c = 'Last',
            Email__c = 'flast@example.com'
        );

        insert testMeetupRegistration;

        Boolean isEmailRegistered = MeetupRegistrationService.isEmailRegistered(testMeetupRegistration.Email__c, testMeetup.Id);
        System.assert(isEmailRegistered, 'Expected true as we have already inserted a registration for this email and meetup.');
    }

    @isTest
    private static void isEmailRegistered_noExistingRegistration_expectFalse(){
        Meetup__c testMeetup = new Meetup__c(
            Name = 'Unit Test Meetup',
            Status__c = 'Open',
            RegistrationLimit__c = 1
        );

        insert testMeetup;

        MeetupRegistration__c testMeetupRegistration = new MeetupRegistration__c(
            Meetup__c = testMeetup.Id,
            FirstName__c = 'First',
            LastName__c = 'Last',
            Email__c = 'flast@example.com'
        );

        insert testMeetupRegistration;

        Boolean isEmailRegistered = MeetupRegistrationService.isEmailRegistered('other@example.com', testMeetup.Id);
        System.assert(!isEmailRegistered, 'Expected false as no registration has been created for this email yet.');
    }
}