force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Represents an event meetup, which users can register for.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>A generated code that can be used to find this meetup on the registration page.</description>
    <externalId>true</externalId>
    <inlineHelpText>A generated code that can be used to find this meetup on the registration page.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The max number of registrations allowed for this Meetup.</description>
    <inlineHelpText>The max number of registrations allowed for this Meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Meetup.</description>
    <inlineHelpText>The status of the Meetup.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MeetupTriggerHandlerTest.cls
@isTest
private with sharing class MeetupTriggerHandlerTest {

    @isTest
    private static void onBeforeInsert_expectRegistrationCodeGenerated() {
        Meetup__c testMeetup = new Meetup__c(
            Name = 'Unit Test Meetup',
            Status__c = 'Open',
            RegistrationLimit__c = 1
        );

        insert testMeetup;

        testMeetup = [SELECT Id, RegistrationCode__c FROM Meetup__c WHERE Id = :testMeetup.Id];

        System.assertNotEquals(null, testMeetup.RegistrationCode__c, 
            'Expected a registration code to be generated for the meetup when inserted.');
    }
}