force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Represents an event meetup, which users can register for.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The max number of registrations allowed for this Meetup.</description>
    <inlineHelpText>The max number of registrations allowed for this Meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Meetup.</description>
    <inlineHelpText>The status of the Meetup.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Represents an individual registration for a related meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The registrant&apos;s email address.</description>
    <inlineHelpText>The registrant&apos;s email address.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup that this registration relates to.</description>
    <inlineHelpText>The meetup that this registration relates to.</inlineHelpText>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>MeetupRegistrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationTriggerHandler.cls
/* 
* @description Responsible for all Meetup Registration sObject trigger behaviors.
*/
public with sharing class MeetupRegistrationTriggerHandler {
    public void onBeforeInsert(List<MeetupRegistration__c> meetupRegistrationRecords) {
        validateRegistrations(meetupRegistrationRecords);
    }

    public void validateRegistrations(List<MeetupRegistration__c> meetupRegistrationRecords){
        Map<Id, List<MeetupRegistration__c>> registrationsByMeetupId = new Map<Id, List<MeetupRegistration__c>>();
        for (MeetupRegistration__c registration : meetupRegistrationRecords) {
            if (registrationsByMeetupId.containsKey(registration.Meetup__c)) {
                registrationsByMeetupId.get(registration.Meetup__c).add(registration);
            } else {
                registrationsByMeetupId.put(registration.Meetup__c, new List<MeetupRegistration__c> { registration });
            }
        }

        List<Meetup__c> relatedMeetups = [
            SELECT Id, Name, RegistrationLimit__c, Status__c,
                (SELECT Id, Email__c 
                FROM MeetupRegistrations__r)
            FROM Meetup__c
            WHERE Id IN :registrationsByMeetupId.keySet()
        ];

        for (Meetup__c meetup : relatedMeetups) {
            Integer remainingCapacity = Integer.valueOf(meetup.RegistrationLimit__c) - meetup.MeetupRegistrations__r.size();
            List<MeetupRegistration__c> relatedRegs = registrationsByMeetupId.get(meetup.Id);

            Set<String> existingEmails = new Set<String>();
            for (MeetupRegistration__c existingReg : meetup.MeetupRegistrations__r) {
                existingEmails.add(existingReg.Email__c);
            }
            
            for (MeetupRegistration__c relatedReg : relatedRegs) {
                if (meetup.Status__c == 'Closed') {
                    relatedReg.addError('Registrations cannot be made for meetup '  + meetup.Name + ' because it is closed.');
                    continue;
                }

                if (remainingCapacity <= 0) {
                    relatedReg.addError('Registrations cannot be made for the meetup ' + meetup.Name + ' at maximum capacity.');
                    continue;
                }

                if (existingEmails.contains(relatedReg.Email__c)) {
                    relatedReg.addError('An existing registration for meetup ' + meetup.Name + ' with email ' + relatedReg.Email__c + ' already exists.');
                    continue;
                }

                // Keep track in case we hit capacity mid-loop or duplicate emails were inserted in the same transaction.
                existingEmails.add(relatedReg.Email__c);
                remainingCapacity--;
            }
        }
    }

}